config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "sequences#index"

  resources :sequences
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sequence.rb
class Sequence < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :sequences
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    end

end

app/controllers/sequences_controller.rb
class SequencesController < ApplicationController
  before_action :set_sequence, only: [:show, :edit, :update, :destroy]
  

  def index
    @sequences = current_user.sequences
  end


  def show
  end


  def new
    @sequence = Sequence.new
  end


  def create
    @sequence = current_user.sequences.new(sequence_params)

    if @sequence.save
      # flash[:success] = "New Flow Formed"
      redirect_to sequences_path
    else
      binding.pry
      # flash[:error] = "Error #{@sequence.errors.full_messages.join("\n")}"
      render :new
    end
  end


  def edit
  end


  def update
    if @sequence.update(sequence_params)
      redirect_to sequence_path(@sequence)
    else
      render :edit
    end
  end


  def destroy
    @sequence.destroy
    redirect_to sequences_path
  end

  private
    def set_sequence
      @sequence = current_user.sequences.find(params[:id])
    end

    def sequence_params
      params.require(:sequence).permit(:name, :body)
    end
    
end

app/helpers/sequences_helper.rb
module SequencesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YogaRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/sequences/edit.html.erb
<h1> Change It Up </h1>

<%= form_with(model: @sequence, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, required: true, placeholder: "Flow" %>
  </div>


  <%= f.submit %>

<% end %>

app/views/sequences/index.html.erb
<%= button_to "Log Out", destroy_user_session_path, method: :delete %>
<h2> Welcome <%= current_user.first_name %> </h2>

<hr />

<%= link_to 'Create New Sequence', new_sequence_path %>

<br/>
<br/>

  <% @sequences.each do |sequence| %>
    <li>
      <%= link_to "#{sequence.name}", sequence_path(sequence) %>
    </li>
  
    <% end %>

app/views/sequences/new.html.erb
<h1> Add Sequence </h1>

<%= form_with(model: @sequence, local: true) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Name" %>
  </div>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body, required: true, placeholder: "Flow" %>
  </div>


  <%= f.submit %>

<% end %>

app/views/sequences/show.html.erb
<h1> Namaste <%= current_user.first_name %> </h1>
<h3> Let's Flow </h3>

  <%= @sequence.name %> :
<br/>
  <%= @sequence.body %>

<br/>
<br/>

  <%= link_to 'Edit Sequence', edit_sequence_path(@sequence) %>
  <br/>
  <%= link_to 'Delete Sequence', sequence_path(@sequence), method: :delete %>
  <br/>
  <%= link_to 'Back', sequences_path %>